language: groovy
sudo: required
dist: precise
cache:
  directories:
  - $HOME/.m2
  - $HOME/.grails/ivy-cache
  - $HOME/.grails/wrapper
jdk:
- oraclejdk7
before_script:
- chmod +x grailsw test/test-restful-api/grailsw
script: "./grailsw clean && ./grailsw refresh-dependencies && ./grailsw compile &&
  cd test/test-restful-api && ./grailsw clean && ./grailsw refresh-dependencies &&
  ./grailsw compile && ./grailsw test-app"
